# Generated by Django 5.0 on 2023-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=500)),
                ('category', models.IntegerField(choices=[(1, 'Mobiles'), (2, 'Clothes'), (3, 'Books'), (4, 'Shoes')])),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
