# Generated by Django 5.0 on 2024-01-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YogaApp', '0005_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_signature',
        ),
    ]
